- name: install mysql db
  apt: name=mysql-server state=present
  become: yes
  become_method: sudo

- name: installs python-mysqldb
  become: yes
  become_method: sudo
  apt: name=python-mysqldb state=present

- name: start mysql
  become: yes
  become_method: sudo
  service: name=mysql state=started

- name: set bind address
  become: yes
  become_method: sudo
  lineinfile: dest=/etc/mysql/my.cnf
    line='bind-address = 0.0.0.0'
    state=present
    regexp=^bind-address(.*)
  notify: restart mysql

- name: creates db user dba
  become: yes
  become_method: sudo
  mysql_user: name=dba password=g3h31m priv=*.*:ALL,GRANT state=present host=%  
